# docker-compose.yml  (Prometheus + Grafana; run API locally with run.sh)
version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: aegis_prom
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/rules.yml:/etc/prometheus/rules.yml:ro   # <â€” add this
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: aegis_grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
