global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "aegis-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  # (optional) scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

rule_files:
  - /etc/prometheus/rules.yml
